name: poziomka
services:
  poziomka_blob:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    ports:
      - 10000:10000
    volumes:
      - blob_data:/data/blob
    command:
      azurite-blob --blobHost 0.0.0.0 -l /data/blob

  poziomka_mail:
    image: changemakerstudiosus/papercut-smtp:latest
    ports:
      - 80:80
      - 25:25

  poziomka_db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - MSSQL_SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - 1433:1433
    volumes:
      - db_data:/data/db

  poziomka_api:
    build:
      context: .
      dockerfile: PoZiomkaApi/Dockerfile
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      - DB_CONNECTION_STRING=Server=poziomka_db;Database=PoziomkaDB;User Id=SA;Password=Pass@word;TrustServerCertificate=true;Encrypt=false
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    volumes:
      - ~/AppData/Roaming/ASP.NET/Https:/root/.aspnet/https:ro
      - ~/AppData/Roaming/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    depends_on:
      - poziomka_db

  poziomka_app:
    build:
      context: PoZiomkaApp
    environment:
      - API_DOMAIN=poziomka_api
      - API_PORT=8081
    ports:
      - 4200:4200
    depends_on:
      - poziomka_api

volumes:
  db_data:
  blob_data: