name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  Build-And-Deploy:
    name: Build and Deploy Angular App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_POND_02473A803 }}
          action: "upload"
          app_location: "./PoZiomkaApp"
          output_location: "dist/poziomka.client/browser"
